# Generated by Django 2.2.7 on 2019-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20191120_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('option5', models.CharField(max_length=100)),
                ('option6', models.CharField(max_length=100)),
            ],
        ),
    ]
