# Generated by Django 2.2.7 on 2019-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_questiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
