# Generated by Django 2.2.7 on 2019-12-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_questiondata_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
